#
# This file should be duplicated for production to have the actual stripe key.
#
version: "3"
services:
  web:
    build: .
    environment:
      - RACK_ENV=production
      - STRIPE_SECRET_KEY=sk_test_CQSxADZNxofHzSGPBcWVXtux
      - STRIPE_PUB_KEY=pk_test_Tqhn4yVmoycEvi5HdSd3i9XF

  proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    restart: always

volumes:
  certs:
  certs-data:
